python -m trainer.train \
    --device cpu \
    --src_language en \
    --tgt_language en \
    --src_path D:\jinrenren\NLP_study\codes\NMT\data\src.en \
    --tgt_path D:\jinrenren\NLP_study\codes\NMT\data\tgt.en \
    --src_vocab_path D:\jinrenren\NLP_study\codes\NMT\data\src.en.vocab \
    --tgt_vocab_path D:\jinrenren\NLP_study\codes\NMT\data\tgt.en.vocab \
    --rnn_type rnn \
    --embedding_size 128 \
    --hidden_size 128 \
    --num_layers 3